# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.15

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /usr/technopark

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /usr/technopark/test

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /usr/technopark/test/CMakeFiles /usr/technopark/test/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /usr/technopark/test/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named tests

# Build rule for target.
tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tests
.PHONY : tests

# fast build rule for target.
tests/fast:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/build
.PHONY : tests/fast

#=============================================================================
# Target rules for targets named prog

# Build rule for target.
prog: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 prog
.PHONY : prog

# fast build rule for target.
prog/fast:
	$(MAKE) -f CMakeFiles/prog.dir/build.make CMakeFiles/prog.dir/build
.PHONY : prog/fast

#=============================================================================
# Target rules for targets named my_lib

# Build rule for target.
my_lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 my_lib
.PHONY : my_lib

# fast build rule for target.
my_lib/fast:
	$(MAKE) -f CMakeFiles/my_lib.dir/build.make CMakeFiles/my_lib.dir/build
.PHONY : my_lib/fast

begin.o: begin.cpp.o

.PHONY : begin.o

# target to build an object file
begin.cpp.o:
	$(MAKE) -f CMakeFiles/prog.dir/build.make CMakeFiles/prog.dir/begin.cpp.o
.PHONY : begin.cpp.o

begin.i: begin.cpp.i

.PHONY : begin.i

# target to preprocess a source file
begin.cpp.i:
	$(MAKE) -f CMakeFiles/prog.dir/build.make CMakeFiles/prog.dir/begin.cpp.i
.PHONY : begin.cpp.i

begin.s: begin.cpp.s

.PHONY : begin.s

# target to generate assembly for a file
begin.cpp.s:
	$(MAKE) -f CMakeFiles/prog.dir/build.make CMakeFiles/prog.dir/begin.cpp.s
.PHONY : begin.cpp.s

matrix.o: matrix.cpp.o

.PHONY : matrix.o

# target to build an object file
matrix.cpp.o:
	$(MAKE) -f CMakeFiles/my_lib.dir/build.make CMakeFiles/my_lib.dir/matrix.cpp.o
.PHONY : matrix.cpp.o

matrix.i: matrix.cpp.i

.PHONY : matrix.i

# target to preprocess a source file
matrix.cpp.i:
	$(MAKE) -f CMakeFiles/my_lib.dir/build.make CMakeFiles/my_lib.dir/matrix.cpp.i
.PHONY : matrix.cpp.i

matrix.s: matrix.cpp.s

.PHONY : matrix.s

# target to generate assembly for a file
matrix.cpp.s:
	$(MAKE) -f CMakeFiles/my_lib.dir/build.make CMakeFiles/my_lib.dir/matrix.cpp.s
.PHONY : matrix.cpp.s

tests.o: tests.cpp.o

.PHONY : tests.o

# target to build an object file
tests.cpp.o:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests.cpp.o
.PHONY : tests.cpp.o

tests.i: tests.cpp.i

.PHONY : tests.i

# target to preprocess a source file
tests.cpp.i:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests.cpp.i
.PHONY : tests.cpp.i

tests.s: tests.cpp.s

.PHONY : tests.s

# target to generate assembly for a file
tests.cpp.s:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests.cpp.s
.PHONY : tests.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... tests"
	@echo "... prog"
	@echo "... rebuild_cache"
	@echo "... my_lib"
	@echo "... begin.o"
	@echo "... begin.i"
	@echo "... begin.s"
	@echo "... matrix.o"
	@echo "... matrix.i"
	@echo "... matrix.s"
	@echo "... tests.o"
	@echo "... tests.i"
	@echo "... tests.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

